/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AllowlistClientUpgradeable,
  AllowlistClientUpgradeableInterface,
} from "../AllowlistClientUpgradeable";

const _abi = [
  {
    inputs: [],
    name: "AllowlistZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldAllowlist",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAllowlist",
        type: "address",
      },
    ],
    name: "AllowlistSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "allowlist",
    outputs: [
      {
        internalType: "contract IAllowlist",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "allowlist",
        type: "address",
      },
    ],
    name: "setAllowlist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AllowlistClientUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): AllowlistClientUpgradeableInterface {
    return new utils.Interface(_abi) as AllowlistClientUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AllowlistClientUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AllowlistClientUpgradeable;
  }
}
