/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AllowlistClient,
  AllowlistClientInterface,
} from "../AllowlistClient";

const _abi = [
  {
    inputs: [],
    name: "AllowlistZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldAllowlist",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAllowlist",
        type: "address",
      },
    ],
    name: "AllowlistSet",
    type: "event",
  },
  {
    inputs: [],
    name: "allowlist",
    outputs: [
      {
        internalType: "contract IAllowlist",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "allowlist",
        type: "address",
      },
    ],
    name: "setAllowlist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AllowlistClient__factory {
  static readonly abi = _abi;
  static createInterface(): AllowlistClientInterface {
    return new utils.Interface(_abi) as AllowlistClientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AllowlistClient {
    return new Contract(address, _abi, signerOrProvider) as AllowlistClient;
  }
}
