/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMulticall, IMulticallInterface } from "../IMulticall";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
        ],
        internalType: "struct IMulticall.ExCallData[]",
        name: "exdata",
        type: "tuple[]",
      },
    ],
    name: "multiexcall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMulticall__factory {
  static readonly abi = _abi;
  static createInterface(): IMulticallInterface {
    return new utils.Interface(_abi) as IMulticallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMulticall {
    return new Contract(address, _abi, signerOrProvider) as IMulticall;
  }
}
