/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPricerReader, IPricerReaderInterface } from "../IPricerReader";

const _abi = [
  {
    inputs: [],
    name: "getLatestPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "priceId",
        type: "uint256",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPricerReader__factory {
  static readonly abi = _abi;
  static createInterface(): IPricerReaderInterface {
    return new utils.Interface(_abi) as IPricerReaderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPricerReader {
    return new Contract(address, _abi, signerOrProvider) as IPricerReader;
  }
}
