/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRWAOracle, IRWAOracleInterface } from "../IRWAOracle";

const _abi = [
  {
    inputs: [],
    name: "getPriceData",
    outputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRWAOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IRWAOracleInterface {
    return new utils.Interface(_abi) as IRWAOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRWAOracle {
    return new Contract(address, _abi, signerOrProvider) as IRWAOracle;
  }
}
