/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRWAOracleSetter,
  IRWAOracleSetterInterface,
} from "../IRWAOracleSetter";

const _abi = [
  {
    inputs: [],
    name: "getPriceData",
    outputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRWAOracleSetter__factory {
  static readonly abi = _abi;
  static createInterface(): IRWAOracleSetterInterface {
    return new utils.Interface(_abi) as IRWAOracleSetterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRWAOracleSetter {
    return new Contract(address, _abi, signerOrProvider) as IRWAOracleSetter;
  }
}
