/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRWAHubNonStableInstantMint,
  IRWAHubNonStableInstantMintInterface,
} from "../IRWAHubNonStableInstantMint";

const _abi = [
  {
    inputs: [],
    name: "CannotClaimExcess",
    type: "error",
  },
  {
    inputs: [],
    name: "CannotClaimMint",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "ClaimExcessPaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "ClaimExcessUnpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalRWAOwed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rwaExcessDue",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rwaExcessGiven",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "priceClaimed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "depositId",
        type: "bytes32",
      },
    ],
    name: "ExcessMintClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralAmountDeposited",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralAmountAfterFees",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feesInCollateral",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rwaGiven",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "priceMinted",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "depositId",
        type: "bytes32",
      },
    ],
    name: "InstantMint",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldInstantMintBps",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newInstantMintBps",
        type: "uint256",
      },
    ],
    name: "InstantMintAmountSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldInstantMintAssetManager",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newInstantMintAssetManager",
        type: "address",
      },
    ],
    name: "InstantMintAssetManagerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newFee",
        type: "uint256",
      },
    ],
    name: "InstantMintFeeSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "depositId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldGivenAmt",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newGivenAmt",
        type: "uint256",
      },
    ],
    name: "InstantMintGivenOverriden",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "InstantMintPaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "InstantMintUnpaused",
    type: "event",
  },
];

export class IRWAHubNonStableInstantMint__factory {
  static readonly abi = _abi;
  static createInterface(): IRWAHubNonStableInstantMintInterface {
    return new utils.Interface(_abi) as IRWAHubNonStableInstantMintInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRWAHubNonStableInstantMint {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRWAHubNonStableInstantMint;
  }
}
