/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRWAHubOffChainRedemptions,
  IRWAHubOffChainRedemptionsInterface,
} from "../IRWAHubOffChainRedemptions";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldMinimum",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newMinimum",
        type: "uint256",
      },
    ],
    name: "OffChainRedemptionMinimumSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "OffChainRedemptionPaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "OffChainRedemptionUnpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "redemptionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rwaTokenAmountIn",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "offChainDestination",
        type: "bytes32",
      },
    ],
    name: "RedemptionRequestedServicedOffChain",
    type: "event",
  },
  {
    inputs: [],
    name: "pauseOffChainRedemption",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountRWATokenToRedeem",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "offChainDestination",
        type: "bytes32",
      },
    ],
    name: "requestRedemptionServicedOffchain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minimumAmount",
        type: "uint256",
      },
    ],
    name: "setOffChainRedemptionMinimum",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpauseOffChainRedemption",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRWAHubOffChainRedemptions__factory {
  static readonly abi = _abi;
  static createInterface(): IRWAHubOffChainRedemptionsInterface {
    return new utils.Interface(_abi) as IRWAHubOffChainRedemptionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRWAHubOffChainRedemptions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRWAHubOffChainRedemptions;
  }
}
