/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISanctionsList,
  ISanctionsListInterface,
} from "../ISanctionsList";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "isSanctioned",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISanctionsList__factory {
  static readonly abi = _abi;
  static createInterface(): ISanctionsListInterface {
    return new utils.Interface(_abi) as ISanctionsListInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISanctionsList {
    return new Contract(address, _abi, signerOrProvider) as ISanctionsList;
  }
}
