version: '3.1'
name: rwa-services
services:
  rwadb:
    container_name: rwadb
    image: postgres:15.6-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rwa
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5434:5432
    expose:
      - 5434
    networks:
      - rwa
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - backend/config/.env
    depends_on:
      rwadb:
        condition: service_healthy
    ports:
      - 3001:3000
    expose:
      - 3001
    restart: always
    networks:
      - rwa
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      args:
        - APPENV=dev
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - rwa
networks:
  rwa: 
    driver: bridge
volumes:
  cache:
    driver: local