/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBlocklistClientInterface extends ethers.utils.Interface {
  functions: {
    "blocklist()": FunctionFragment;
    "setBlocklist(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "blocklist", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBlocklist",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "blocklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBlocklist",
    data: BytesLike
  ): Result;

  events: {
    "BlocklistSet(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BlocklistSet"): EventFragment;
}

export type BlocklistSetEvent = TypedEvent<
  [string, string] & { oldBlocklist: string; newBlocklist: string }
>;

export class IBlocklistClient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBlocklistClientInterface;

  functions: {
    blocklist(overrides?: CallOverrides): Promise<[string]>;

    setBlocklist(
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  blocklist(overrides?: CallOverrides): Promise<string>;

  setBlocklist(
    registry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    blocklist(overrides?: CallOverrides): Promise<string>;

    setBlocklist(registry: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "BlocklistSet(address,address)"(
      oldBlocklist?: null,
      newBlocklist?: null
    ): TypedEventFilter<
      [string, string],
      { oldBlocklist: string; newBlocklist: string }
    >;

    BlocklistSet(
      oldBlocklist?: null,
      newBlocklist?: null
    ): TypedEventFilter<
      [string, string],
      { oldBlocklist: string; newBlocklist: string }
    >;
  };

  estimateGas: {
    blocklist(overrides?: CallOverrides): Promise<BigNumber>;

    setBlocklist(
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    blocklist(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBlocklist(
      registry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
