/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SanctionsListClientInterface extends ethers.utils.Interface {
  functions: {
    "sanctionsList()": FunctionFragment;
    "setSanctionsList(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "sanctionsList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSanctionsList",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "sanctionsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSanctionsList",
    data: BytesLike
  ): Result;

  events: {
    "SanctionsListSet(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SanctionsListSet"): EventFragment;
}

export type SanctionsListSetEvent = TypedEvent<
  [string, string] & { oldSanctionsList: string; newSanctionsList: string }
>;

export class SanctionsListClient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SanctionsListClientInterface;

  functions: {
    sanctionsList(overrides?: CallOverrides): Promise<[string]>;

    setSanctionsList(
      sanctionsList: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  sanctionsList(overrides?: CallOverrides): Promise<string>;

  setSanctionsList(
    sanctionsList: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    sanctionsList(overrides?: CallOverrides): Promise<string>;

    setSanctionsList(
      sanctionsList: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SanctionsListSet(address,address)"(
      oldSanctionsList?: null,
      newSanctionsList?: null
    ): TypedEventFilter<
      [string, string],
      { oldSanctionsList: string; newSanctionsList: string }
    >;

    SanctionsListSet(
      oldSanctionsList?: null,
      newSanctionsList?: null
    ): TypedEventFilter<
      [string, string],
      { oldSanctionsList: string; newSanctionsList: string }
    >;
  };

  estimateGas: {
    sanctionsList(overrides?: CallOverrides): Promise<BigNumber>;

    setSanctionsList(
      sanctionsList: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    sanctionsList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setSanctionsList(
      sanctionsList: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
